export const DICTIONARY = {
  en: {
    brandSubtitle: "Edge-AI Multi-Modal Fire Defense Grid",
    liveConsole: "Live Command Console",
    tacticalGIS: "Tactical GIS Map",
    incidentForensics: "Forensics & Logs",
    actuationCenter: "Actuation Center",
    networkNodes: "Cadastral Nodes",
    settings: "Emergency Settings",
    subscription: "Coverage Plans",
    systemSecure: "SECURE · GRID NOMINAL",
    fireDetected: "🚨 FIRE DETECTED! MULTI-TIER MITIGATION ACTIVE 🚨",
    flameConfidence: "Flame Confidence",
    flickerHz: "FFT Flicker Frequency",
    fireRiskIndex: "Fire Risk Index (FRI)",
    threatLevel: "Threat Level",
    smokeDensity: "Smoke Density",
    tempGradient: "Rate of Rise (ΔT/Δt)",
    ambientTemp: "Ambient Temp",
    humidity: "Relative Humidity",
    gasConcentration: "Gas / Smoke (PPM)",
    windVector: "Wind Vector",
    sprinklerGrid: "Sprinkler Grid Relay",
    sprinklersActive: "SPRINKLER GRID ACTIVE",
    sprinklersOff: "SPRINKLER GRID STANDBY",
    sirenArray: "110dB LoRa Siren Array",
    sirenActive: "SIREN ACTIVE",
    sirenOff: "SIREN OFF",
    directDispatch: "Station 42 Direct Dispatch",
    callingDispatch: "Connecting to Dispatch...",
    callDispatch: "🚒 Dispatch Fire Brigade",
    exportForensicPDF: "📄 Export Forensic Audit Report",
    registeredFarms: "Registered Cadastral Plots",
    livestock: "Livestock",
    crop: "Crop",
    timeToImpact: "Time to Impact (TTI)",
    statusOnline: "ONLINE",
    statusEvacuate: "CRITICAL EVACUATE",
    statusWarning: "WARNING",
    statusSafe: "SAFE",
    radarHorizon: "500m Optical Horizon",
    rothermelROS: "Rothermel Rate of Spread",
    sha256Proof: "SHA-256 Chained Forensic Hash",
    activeIncidents: "Active Emergency Incidents",
    resolvedIncidents: "Resolved History Logs",
  },
  hi: {
    brandSubtitle: "एज-एआई मल्टी-मोडल अग्नि सुरक्षा ग्रिड",
    liveConsole: "लाइव कमांड कंसोल",
    tacticalGIS: "टैक्टिकल जीआईएस नक्शा",
    incidentForensics: "फॉरेंसिक और लॉग्स",
    actuationCenter: "नियंत्रण केंद्र (Actuation)",
    networkNodes: "पंजीकृत किसान प्लॉट",
    settings: "आपातकालीन सेटिंग्स",
    subscription: "सुरक्षा योजनाएं",
    systemSecure: "सुरक्षित · ग्रिड सामान्य",
    fireDetected: "🚨 आग का पता चला! स्वचालित सुरक्षा सक्रिय 🚨",
    flameConfidence: "आग की संभावना (Confidence)",
    flickerHz: "लपट कंपन आवृत्ति (FFT Flicker)",
    fireRiskIndex: "अग्नि जोखिम सूचकांक (FRI)",
    threatLevel: "खतरे का स्तर",
    smokeDensity: "धुएं का घनत्व",
    tempGradient: "तापमान वृद्धि दर (ΔT/Δt)",
    ambientTemp: "परिवेशी तापमान",
    humidity: "सापेक्ष आर्द्रता (Humidity)",
    gasConcentration: "गैस / धुआं (PPM)",
    windVector: "हवा की दिशा व गति",
    sprinklerGrid: "स्प्रिंकलर ग्रिड रिले",
    sprinklersActive: "स्प्रिंकलर ग्रिड सक्रिय (Mist On)",
    sprinklersOff: "स्प्रिंकलर स्टैंडबाय",
    sirenArray: "110dB लोरा सायरन ग्रिड",
    sirenActive: "सायरन बज रहा है",
    sirenOff: "सायरन बंद",
    directDispatch: "स्टेशन 42 आपातकालीन कॉल",
    callingDispatch: "फायर स्टेशन से संपर्क हो रहा है...",
    callDispatch: "🚒 दमकल को सूचित करें",
    exportForensicPDF: "📄 फॉरेंसिक ऑडिट रिपोर्ट डाउनलोड करें",
    registeredFarms: "पंजीकृत किसान भूखंड",
    livestock: "मवेशी (Livestock)",
    crop: "फसल (Crop)",
    timeToImpact: "आग पहुंचने का समय (TTI)",
    statusOnline: "सक्रिय (Online)",
    statusEvacuate: "तत्काल खाली करें (Evacuate)",
    statusWarning: "सतर्क रहें (Warning)",
    statusSafe: "सुरक्षित (Safe)",
    radarHorizon: "500 मी. ऑप्टिकल कवरेज",
    rothermelROS: "रोथर्मेल अग्नि प्रसार दर",
    sha256Proof: "SHA-256 प्रमाणित फॉरेंसिक हैश",
    activeIncidents: "सक्रिय आपातकालीन घटनाएं",
    resolvedIncidents: "सुलझाई गई घटनाओं का इतिहास",
  },
  mr: {
    brandSubtitle: "एज-एआय बहु-मोडल आग संरक्षण ग्रिड",
    liveConsole: "थेट कमांड कन्सोल",
    tacticalGIS: "टॅक्टिकल जीआयएस नकाशा",
    incidentForensics: "फॉरेन्सिक्स आणि नोंदी",
    actuationCenter: "नियंत्रण केंद्र",
    networkNodes: "नोंदणीकृत शेतकरी गट",
    settings: "आपत्कालीन सेटिंग्ज",
    subscription: "संरक्षण योजना",
    systemSecure: "सुरक्षित · ग्रिड सामान्य",
    fireDetected: "🚨 आग लागल्याचे निष्पन्न! तात्काळ कारवाई सुरू 🚨",
    flameConfidence: "आगीची शक्यता",
    flickerHz: "ज्वाला कंपन वारंवारता",
    fireRiskIndex: "आग धोका निर्देशांक (FRI)",
    threatLevel: "धोका पातळी",
    smokeDensity: "धुराची घनता",
    tempGradient: "तापमान वाढ दर",
    ambientTemp: "सभोवतालचे तापमान",
    humidity: "आर्द्रता",
    gasConcentration: "वायू सांद्रता (PPM)",
    windVector: "वाऱ्याचा वेग व दिशा",
    sprinklerGrid: "स्प्रिंकलर व्हॉल्व्ह रिले",
    sprinklersActive: "स्प्रिंकलर चालू",
    sprinklersOff: "स्प्रिंकलर स्टँडबाय",
    sirenArray: "110dB सायरन यंत्रणा",
    sirenActive: "सायरन सुरू",
    sirenOff: "सायरन बंद",
    directDispatch: "स्टेशन 42 थेट संपर्क",
    callingDispatch: "फायर ब्रिगेडशी संपर्क जोडत आहे...",
    callDispatch: "🚒 अग्निशामक दलास पाचारण करा",
    exportForensicPDF: "📄 फॉरेन्सिक अहवाल डाऊनलोड करा",
    registeredFarms: "नोंदणीकृत शेतजमीन",
    livestock: "जनावरे",
    crop: "पीक",
    timeToImpact: "आग पोहोचण्याची वेळ (TTI)",
    statusOnline: "सक्रिय",
    statusEvacuate: "त्वरित सुरक्षित स्थळी जा",
    statusWarning: "सावधान",
    statusSafe: "सुरक्षित",
    radarHorizon: "500 मी. रडार टप्पा",
    rothermelROS: "अग्नि प्रसार वेग",
    sha256Proof: "SHA-256 सुरक्षित डिजिटल स्वाक्षरी",
    activeIncidents: "सक्रिय आगीच्या घटना",
    resolvedIncidents: "निवारण झालेल्या घटना",
  },
  pa: {
    brandSubtitle: "ਐਜ-ਏਆਈ ਅੱਗ ਸੁਰੱਖਿਆ ਗਰਿੱਡ",
    liveConsole: "ਲਾਈਵ ਕਮਾਂਡ ਕੰਸੋਲ",
    tacticalGIS: "ਜੀਆਈਐਸ ਨਕਸ਼ਾ",
    incidentForensics: "ਫੋਰੈਂਸਿਕ ਰਿਕਾਰਡ",
    actuationCenter: "ਕੰਟਰੋਲ ਕੇਂਦਰ",
    networkNodes: "ਕਿਸਾਨ ਪਲਾਟ",
    settings: "ਐਮਰਜੈਂਸੀ ਸੈਟਿੰਗਜ਼",
    subscription: "ਸੁਰੱਖਿਆ ਪਲਾਨ",
    systemSecure: "ਸੁਰੱਖਿਅਤ · ਗਰਿੱਡ ਠੀਕ ਹੈ",
    fireDetected: "🚨 ਅੱਗ ਲੱਗਣ ਦੀ ਪੁਸ਼ਟੀ! ਬਚਾਅ ਕਾਰਵਾਈ ਸ਼ੁਰੂ 🚨",
    flameConfidence: "ਅੱਗ ਦਾ ਅੰਦਾਜ਼ਾ",
    flickerHz: "ਲਪਟਾਂ ਦੀ ਫ੍ਰੀਕੁਐਂਸੀ (FFT)",
    fireRiskIndex: "ਅੱਗ ਖ਼ਤਰਾ ਸੂਚਕਾਂਕ (FRI)",
    threatLevel: "ਖ਼ਤਰੇ ਦਾ ਪੱਧਰ",
    smokeDensity: "ਧੂੰਏਂ ਦੀ ਘਣਤਾ",
    tempGradient: "ਤਾਪਮਾਨ ਵਾਧਾ ਦਰ",
    ambientTemp: "ਤਾਪਮਾਨ",
    humidity: "ਨਮੀ (Humidity)",
    gasConcentration: "ਗੈਸ / ਧੂੰਆਂ (PPM)",
    windVector: "ਹਵਾ ਦੀ ਦਿਸ਼ਾ ਤੇ ਰਫਤਾਰ",
    sprinklerGrid: "ਸਪ੍ਰਿੰਕਲਰ ਗਰਿੱਡ",
    sprinklersActive: "ਸਪ੍ਰਿੰਕਲਰ ਚਾਲੂ",
    sprinklersOff: "ਸਪ੍ਰਿੰਕਲਰ ਬੰਦ",
    sirenArray: "110dB ਸਾਇਰਨ ਸਿਸਟਮ",
    sirenActive: "ਸਾਇਰਨ ਵੱਜ ਰਿਹਾ ਹੈ",
    sirenOff: "ਸਾਇਰਨ ਬੰਦ",
    directDispatch: "ਸਟੇਸ਼ਨ 42 ਫਾਇਰ ਬ੍ਰਿਗੇਡ",
    callingDispatch: "ਸੰਪਰਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    callDispatch: "🚒 ਫਾਇਰ ਬ੍ਰਿਗੇਡ ਨੂੰ ਸੱਦੋ",
    exportForensicPDF: "📄 ਫੋਰੈਂਸਿਕ ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    registeredFarms: "ਰਜਿਸਟਰਡ ਕਿਸਾਨ ਪਲਾਟ",
    livestock: "ਪਸ਼ੂ (Livestock)",
    crop: "ਫ਼ਸਲ",
    timeToImpact: "ਅੱਗ ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ (TTI)",
    statusOnline: "ਸਰਗਰਮ",
    statusEvacuate: "ਤੁਰੰਤ ਖਾਲੀ ਕਰੋ",
    statusWarning: "ਚੇਤਾਵਨੀ",
    statusSafe: "ਸੁਰੱਖਿਅਤ",
    radarHorizon: "500 ਮੀਟਰ ਰਡਾਰ ਖੇਤਰ",
    rothermelROS: "ਅੱਗ ਫੈਲਣ ਦੀ ਰਫਤਾਰ",
    sha256Proof: "SHA-256 ਡਿਜੀਟਲ ਦਸਤਖ਼ਤ",
    activeIncidents: "ਸਰਗਰਮ ਅੱਗ ਘਟਨਾਵਾਂ",
    resolvedIncidents: "ਹੱਲ ਹੋ ਚੁੱਕੀਆਂ ਘਟਨਾਵਾਂ",
  }
};
